name: Heroku Deploy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test

      - name: Build
        run: go build
