name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v reporter/cmd

      - name: Build
        run: go build -v

  create-release:
    name: Create release

    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    needs: [build]

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          check-latest: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload binaries as build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
          retention-days: 90
      - name: Set tag name for downstream jobs
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - name: Install AWS CLI
        uses: chrislennon/action-aws-cli@v1.1
      - name: Create Cloudfront Invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./scripts/release-cloudfront.sh ${{ secrets.GET_FLAKEBOT_CLOUDFRONT_DISTRIBUTION_ID }}

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
